CREATE TABLE writing (
	writingnum INTEGER AUTO_INCREMENT(1, 1) NOT NULL,
	title CHARACTER VARYING (1073741823) COLLATE iso88591_bin NOT NULL,
	email CHARACTER VARYING (40) COLLATE iso88591_bin NOT NULL,
	[password] CHARACTER VARYING (20) COLLATE iso88591_bin NOT NULL,
	content CHARACTER VARYING (1073741823) COLLATE iso88591_bin,
	filepath CHARACTER VARYING (1073741823) COLLATE iso88591_bin,
	CONSTRAINT pk_writing PRIMARY KEY(writingnum)
)
COLLATE utf8_bin;


CREATE TABLE LOG
(writingnum INTEGER NOT NULL, lognum INTEGER AUTO_INCREMENT(1, 1) NOT NULL, changetime DATETIME NOT NULL, CONSTRAINT pk_log PRIMARY KEY(lognum, writingnum), CONSTRAINT fk_writing_to_log FOREIGN KEY(writingnum) REFERENCES writing(writingnum) ON DELETE RESTRICT ON UPDATE RESTRICT) COLLATE utf8_bin;

